---
- hosts: all
  become: yes
  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: installed
    - name: restart nginx
      service:
        name: nginx
        state: restarted


