---
- hosts: server1
  vars:
    vault_token: '<vault-token>'
    vault_url: '<ip- need to enter>:8200'
    vault_pass: "{{lookup('hashi_vault', 'secret=secret/data/firstpass:data token={{ vault_token }} url={{ vault_url }}') }}"
  tasks:
  - name: Hashivault integration with Ansible
    debug:
      msg: "Retrieve password from Hashivault {{ vault_pass }}"
