---
- hosts: all
  become: yes
  tasks:
    - name: To install nginx
      yum:
        name: nginx
        state: latest

    - name: To start nginx
      service:
        name: nginx
        state: started

    - name: To stop nginx
      service:
        name: nginx
        state: stopped

    - name: To uninstall nginx
      yum:
        name: nginx
        state: absent

